(defun pretty-print (table)
  (let ((rows (list table)))
    (if (null rows)
        (format t "Input table is empty!~%")
        (let ((colums '()))   
            (maphash (lambda (key value)
                       (push key colums))
                     (first rows))
          (format t "~%")
          (dolist (colum colums) (format t "~15A" colum))
          (format t "~%")
          (dolist (colum colums)
            (declare (ignore colum))
            (format t "---------------"))
          (format t "~%")

          (dolist (row rows)
            (dolist (col colums)
              (format t "~15a" (gethash col row)))
            (format t "~%"))))
    t))

(defun company-record (line)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash :id ht) (parse-integer (first line)))
    (setf (gethash :name ht) (second line))
    (setf (gethash :country ht) (third line))
    (setf (gethash :founder ht) (cadddr line))
    ht))

(defun spacecraft-record (line)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash :id ht) (parse-integer (first line)))
    (setf (gethash :name ht) (second line))
    (setf (gethash :type ht) (third line))
    (setf (gethash :company-id ht) (parse-integer (cadddr line)))))

(defun read-csv (file-hash file-type)
  (let ((ht (make-hash-table :test 'equal)))
  (with-open-file (stream file-hash)
    (do ((line (read-line stream nil) (read-line stream nil)))
        ((null line) ht)
      (let* ((clean-line (string-trim '(#\Space #\Tab #\Return #\Newline) line))
             (breaking (uiop:split-string clean-line :separator ","))
             (record (case file-type
                       (:companies (company-record breaking))
                       (:spacecrafts (spacecraft-record breaking))))
             (record-id (gethash :id record)))
        (setf (gethash record-id ht) record))))

    (lambda (&key (id nil))
      (cond
        (id (pretty-print (gethash id ht)))
        (t (format t "nooo"))))))


(funcall (read-csv "c:/Users/dmanu/portacle/Lisp_5/companies.csv" :companies) :id 1) 
